import Sidebar from "./Sidebar";
import Topbar from "./Topbar";

function CareerRoadmap() {
  const roadmap = [
    {
      week: "Week 1",
      title: "HTML, CSS & JavaScript",
      status: "Completed",
      color: "bg-green-500",
    },
    {
      week: "Week 2",
      title: "React.js Fundamentals",
      status: "In Progress",
      color: "bg-cyan-500",
    },
    {
      week: "Week 3",
      title: "Advanced React + APIs",
      status: "Upcoming",
      color: "bg-slate-600",
    },
    {
      week: "Week 4",
      title: "Resume & Portfolio",
      status: "Upcoming",
      color: "bg-slate-600",
    },
    {
      week: "Week 5",
      title: "Interview Preparation",
      status: "Upcoming",
      color: "bg-slate-600",
    },
    {
      week: "Week 6",
      title: "Placement Ready",
      status: "Goal",
      color: "bg-yellow-500",
    },
  ];

  return (
    <div className="flex bg-slate-900 min-h-screen">

      <Sidebar />

      <div className="flex-1">

        <Topbar />

        <div className="p-8">

          <h1 className="text-4xl font-bold text-white">
            AI Career Roadmap
          </h1>

          <p className="text-slate-400 mt-2">
            Personalized learning roadmap generated by AI.
          </p>

          {/* Career Goal */}

          <div className="mt-10 bg-slate-800 rounded-3xl p-8 border border-slate-700">

            <h2 className="text-cyan-400 text-xl font-semibold">
              🎯 Career Goal
            </h2>

            <h1 className="text-4xl font-bold text-white mt-4">
              Frontend React Developer
            </h1>

            <p className="text-slate-400 mt-4">
              Complete the roadmap below to become placement-ready.
            </p>

          </div>

          {/* Progress */}

          <div className="mt-8 bg-slate-800 rounded-3xl p-8 border border-slate-700">

            <div className="flex justify-between">

              <h2 className="text-white text-2xl font-bold">
                Overall Progress
              </h2>

              <span className="text-cyan-400 font-bold">
                35%
              </span>

            </div>

            <div className="w-full h-4 bg-slate-700 rounded-full mt-6 overflow-hidden">

              <div
                className="h-full bg-cyan-500 rounded-full transition-all duration-1000"
                style={{ width: "35%" }}
              />

            </div>

          </div>

          {/* Timeline */}

          <div className="mt-10 space-y-6">

            {roadmap.map((item) => (

              <div
                key={item.week}
                className="bg-slate-800 rounded-2xl p-6 border border-slate-700 hover:border-cyan-500 transition-all duration-300"
              >

                <div className="flex justify-between items-center">

                  <div>

                    <h2 className="text-white text-xl font-bold">
                      {item.week}
                    </h2>

                    <p className="text-slate-400 mt-2">
                      {item.title}
                    </p>

                  </div>

                  <span
                    className={`${item.color} px-4 py-2 rounded-full text-white font-semibold`}
                  >
                    {item.status}
                  </span>

                </div>

              </div>

            ))}

          </div>

        </div>

      </div>

    </div>
  );
}

export default CareerRoadmap;