import { useEffect, useMemo, useState } from "react";
import {
  BookOpen,
  CheckCircle,
  Clock,
  Sparkles,
  ArrowRight,
  Target,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

function LearningRoadmap() {
  const navigate = useNavigate();

  const [analysis, setAnalysis] = useState(null);

  /* =========================================================
     LOAD REAL RESUME ANALYSIS
  ========================================================= */

  useEffect(() => {
    loadAnalysis();

    window.addEventListener(
      "resumeAnalysisUpdated",
      loadAnalysis
    );

    window.addEventListener(
      "storage",
      loadAnalysis
    );

    return () => {
      window.removeEventListener(
        "resumeAnalysisUpdated",
        loadAnalysis
      );

      window.removeEventListener(
        "storage",
        loadAnalysis
      );
    };
  }, []);

  const loadAnalysis = () => {
    const saved =
      localStorage.getItem("resumeAnalysis");

    if (!saved) {
      setAnalysis(null);
      return;
    }

    try {
      const data = JSON.parse(saved);

      const actualAnalysis =
        data?.analysis || data;

      setAnalysis(actualAnalysis);
    } catch (error) {
      console.error(
        "Failed to load roadmap data:",
        error
      );

      setAnalysis(null);
    }
  };

  /* =========================================================
     REAL DATA
  ========================================================= */

  const missingSkills = useMemo(() => {
    if (!Array.isArray(analysis?.missingSkills)) {
      return [];
    }

    return [
      ...new Set(
        analysis.missingSkills
          .filter(Boolean)
          .map((skill) =>
            String(skill).trim()
          )
      ),
    ];
  }, [analysis]);

  const careerGoal =
    analysis?.careerRole ||
    analysis?.careerGoal ||
    analysis?.detectedRole ||
    "your target career";

  /* =========================================================
     ROADMAP
  ========================================================= */

  const roadmap = useMemo(() => {
    if (!analysis) {
      return [];
    }

    /*
     * Prefer roadmap generated by backend/AI
     * when available.
     */

    const backendRoadmap =
      analysis.learningRoadmap ||
      analysis.roadmap;

    if (Array.isArray(backendRoadmap)) {
      return backendRoadmap
        .filter(Boolean)
        .map((item, index) => ({
          title:
            item.title ||
            item.name ||
            `Learning Step ${index + 1}`,

          description:
            item.description ||
            item.details ||
            "Continue developing this skill.",

          duration:
            item.duration ||
            "1 week",

          topics:
            Array.isArray(item.topics)
              ? item.topics
              : item.skill
              ? [item.skill]
              : [],

          completed:
            item.completed === true,
        }));
    }

    /*
     * Otherwise generate roadmap
     * from real missing skills.
     */

    return createRoadmap(missingSkills);
  }, [analysis, missingSkills]);

  /* =========================================================
     EMPTY STATE
  ========================================================= */

  if (!analysis) {
    return (
      <section
        className="
          relative
          overflow-hidden
          rounded-3xl
          border border-white/[0.08]
          bg-[#111827]
          p-6
        "
      >
        <div
          className="
            pointer-events-none
            absolute
            -right-24
            -top-24
            h-52
            w-52
            rounded-full
            bg-cyan-500/[0.06]
            blur-3xl
          "
        />

        <div className="relative z-10">

          <Header />

          <div
            className="
              mt-6
              flex
              flex-col
              items-center
              justify-center
              rounded-2xl
              border border-yellow-400/10
              bg-yellow-400/[0.03]
              px-6
              py-8
              text-center
            "
          >
            <div
              className="
                flex
                h-14
                w-14
                items-center
                justify-center
                rounded-2xl
                bg-yellow-400/10
              "
            >
              <BookOpen
                size={26}
                className="text-yellow-400"
              />
            </div>

            <h3 className="mt-4 text-sm font-semibold text-white">
              Learning roadmap unavailable
            </h3>

            <p className="mt-2 max-w-sm text-xs leading-5 text-slate-500">
              Analyze your resume first to generate
              a personalized learning roadmap based
              on your actual skill gaps.
            </p>
          </div>

        </div>
      </section>
    );
  }

  /* =========================================================
     MAIN
  ========================================================= */

  return (
    <section
      className="
        relative
        overflow-hidden
        rounded-3xl
        border border-white/[0.08]
        bg-[#111827]
        p-6
      "
    >
      {/* =====================================================
          BACKGROUND GLOW
      ===================================================== */}

      <div
        className="
          pointer-events-none
          absolute
          -right-24
          -top-24
          h-52
          w-52
          rounded-full
          bg-cyan-500/[0.06]
          blur-3xl
        "
      />

      <div
        className="
          pointer-events-none
          absolute
          -bottom-24
          -left-24
          h-52
          w-52
          rounded-full
          bg-blue-500/[0.04]
          blur-3xl
        "
      />

      <div className="relative z-10">

        {/* =================================================
            HEADER
        ================================================= */}

        <div className="flex items-center justify-between gap-4">

          <div className="flex items-center gap-3">

            <div
              className="
                flex
                h-11
                w-11
                shrink-0
                items-center
                justify-center
                rounded-xl
                border border-cyan-400/10
                bg-cyan-400/[0.08]
              "
            >
              <Sparkles
                size={21}
                className="text-cyan-400"
              />
            </div>

            <div>

              <div className="flex items-center gap-2">

                <h2 className="text-lg font-bold text-white">
                  Personalized Learning Roadmap
                </h2>

                <span
                  className="
                    hidden
                    rounded-full
                    border border-cyan-400/10
                    bg-cyan-400/[0.05]
                    px-2
                    py-0.5
                    text-[8px]
                    font-semibold
                    uppercase
                    tracking-wider
                    text-cyan-400
                    sm:block
                  "
                >
                  AI
                </span>

              </div>

              <p className="mt-0.5 text-xs text-slate-500">
                Built from your real skill gaps
              </p>

            </div>

          </div>

          <div
            className="
              hidden
              shrink-0
              items-center
              gap-1.5
              rounded-full
              border border-white/[0.07]
              bg-white/[0.03]
              px-3
              py-1.5
              sm:flex
            "
          >
            <Target
              size={11}
              className="text-cyan-400"
            />

            <span className="max-w-[130px] truncate text-[9px] font-semibold text-slate-400">
              {careerGoal}
            </span>
          </div>

        </div>

        {/* =================================================
            ROADMAP
        ================================================= */}

        {roadmap.length === 0 ? (

          <div
            className="
              mt-6
              rounded-2xl
              border border-emerald-400/10
              bg-emerald-400/[0.03]
              p-5
            "
          >

            <div className="flex items-start gap-3">

              <div
                className="
                  flex
                  h-10
                  w-10
                  shrink-0
                  items-center
                  justify-center
                  rounded-xl
                  bg-emerald-400/10
                "
              >
                <CheckCircle
                  size={20}
                  className="text-emerald-400"
                />
              </div>

              <div>

                <h3 className="text-sm font-bold text-emerald-400">
                  Excellent Skill Coverage
                </h3>

                <p className="mt-1.5 text-xs leading-5 text-slate-500">
                  No major skill gaps were detected.
                  Focus on advanced projects, interview
                  preparation and real-world experience.
                </p>

              </div>

            </div>

          </div>

        ) : (

          <div className="mt-6">

            {/* =================================================
                ROADMAP CARDS
            ================================================= */}

            <div
              className="
                grid
                grid-cols-1
                gap-3
                md:grid-cols-2
              "
            >

              {roadmap
                .slice(0, 4)
                .map((item, index) => (
                  <RoadmapCard
                    key={`${item.title}-${index}`}
                    item={item}
                    index={index}
                  />
                ))}

            </div>

            {/* =================================================
                VIEW FULL ROADMAP
            ================================================= */}

            <button
              type="button"
              onClick={() =>
                navigate("/career-roadmap")
              }
              className="
                mt-4
                flex
                w-full
                items-center
                justify-center
                gap-2
                rounded-xl
                border border-white/[0.07]
                bg-white/[0.02]
                py-2.5
                text-xs
                font-semibold
                text-cyan-400
                transition-all
                duration-300
                hover:border-cyan-400/20
                hover:bg-cyan-400/[0.04]
              "
            >
              View Full Learning Roadmap

              <ArrowRight
                size={14}
                className="transition-transform duration-300 group-hover:translate-x-0.5"
              />
            </button>

          </div>

        )}

      </div>
    </section>
  );
}


/* =========================================================
   HEADER
========================================================= */

function Header() {
  return (
    <div className="flex items-center gap-3">

      <div
        className="
          flex
          h-11
          w-11
          shrink-0
          items-center
          justify-center
          rounded-xl
          border border-cyan-400/10
          bg-cyan-400/[0.08]
        "
      >
        <Sparkles
          size={21}
          className="text-cyan-400"
        />
      </div>

      <div>

        <h2 className="text-lg font-bold text-white">
          Personalized Learning Roadmap
        </h2>

        <p className="mt-0.5 text-xs text-slate-500">
          AI-generated roadmap based on your skill gaps
        </p>

      </div>

    </div>
  );
}


/* =========================================================
   ROADMAP CARD
========================================================= */

function RoadmapCard({
  item,
  index,
}) {
  return (
    <div
      className="
        group
        relative
        overflow-hidden
        rounded-2xl
        border border-white/[0.07]
        bg-slate-950/30
        p-4
        transition-all
        duration-300
        hover:-translate-y-0.5
        hover:border-cyan-400/20
        hover:bg-slate-950/50
      "
    >

      {/* Hover Glow */}

      <div
        className="
          pointer-events-none
          absolute
          -right-8
          -top-8
          h-20
          w-20
          rounded-full
          bg-cyan-400/[0.04]
          blur-2xl
          transition-all
          duration-300
          group-hover:bg-cyan-400/[0.08]
        "
      />

      <div className="relative flex gap-3">

        {/* =================================================
            STEP
        ================================================= */}

        <div className="shrink-0">

          <div
            className="
              flex
              h-9
              w-9
              items-center
              justify-center
              rounded-lg
              border border-cyan-400/10
              bg-cyan-400/[0.06]
            "
          >

            {item.completed ? (

              <CheckCircle
                size={18}
                className="text-emerald-400"
              />

            ) : (

              <span className="text-xs font-bold text-cyan-400">
                {index + 1}
              </span>

            )}

          </div>

        </div>

        {/* =================================================
            CONTENT
        ================================================= */}

        <div className="min-w-0 flex-1">

          <div className="flex items-start justify-between gap-2">

            <h3 className="text-sm font-bold leading-5 text-white">
              {item.title}
            </h3>

            {item.duration && (
              <span
                className="
                  flex
                  shrink-0
                  items-center
                  gap-1
                  text-[10px]
                  text-slate-500
                "
              >
                <Clock size={11} />

                {item.duration}
              </span>
            )}

          </div>

          <p
            className="
              mt-1.5
              line-clamp-2
              text-[11px]
              leading-5
              text-slate-500
            "
          >
            {item.description}
          </p>

          {Array.isArray(item.topics) &&
            item.topics.length > 0 && (

              <div className="mt-3 flex flex-wrap gap-1.5">

                {item.topics
                  .slice(0, 4)
                  .map((topic, topicIndex) => (

                    <span
                      key={`${topic}-${topicIndex}`}
                      className="
                        rounded-lg
                        border border-cyan-400/10
                        bg-cyan-400/[0.05]
                        px-2
                        py-1
                        text-[9px]
                        font-medium
                        text-cyan-300
                      "
                    >
                      {topic}
                    </span>

                  ))}

              </div>

            )}

        </div>

      </div>

    </div>
  );
}


/* =========================================================
   CREATE ROADMAP FROM REAL MISSING SKILLS
========================================================= */

function createRoadmap(skills) {

  if (!skills || skills.length === 0) {
    return [
      {
        title: "Advanced Project Development",

        description:
          "Build a production-ready project that demonstrates your existing technical skills.",

        duration: "1–2 weeks",

        topics: [
          "Real-world Project",
          "GitHub",
          "Deployment",
        ],

        completed: false,
      },

      {
        title: "Interview Preparation",

        description:
          "Strengthen your technical and behavioral interview performance.",

        duration: "1 week",

        topics: [
          "DSA",
          "Technical Questions",
          "HR Interview",
        ],

        completed: false,
      },
    ];
  }

  return skills
    .slice(0, 6)
    .map((skill) => {

      const normalized =
        String(skill)
          .toLowerCase()
          .trim();

      let topics = [skill];

      let description =
        `Build practical knowledge and projects using ${skill}.`;

      let duration = "1 week";

      /* =====================================================
         JAVASCRIPT
      ===================================================== */

      if (
        normalized.includes("javascript") ||
        normalized === "js"
      ) {
        topics = [
          "ES6+",
          "DOM",
          "Async JS",
          "APIs",
        ];

        description =
          "Strengthen modern JavaScript fundamentals and asynchronous programming.";

        duration = "1–2 weeks";
      }

      /* =====================================================
         REACT
      ===================================================== */

      else if (
        normalized.includes("react")
      ) {
        topics = [
          "Components",
          "Hooks",
          "State",
          "API Integration",
        ];

        description =
          "Build interactive React applications using modern hooks and API integration.";

        duration = "1–2 weeks";
      }

      /* =====================================================
         NODE
      ===================================================== */

      else if (
        normalized.includes("node")
      ) {
        topics = [
          "Node.js",
          "Express",
          "REST API",
          "Authentication",
        ];

        description =
          "Learn backend development with Node.js and build production-ready REST APIs.";

        duration = "2 weeks";
      }

      /* =====================================================
         SQL / DATABASE
      ===================================================== */

      else if (
        normalized.includes("sql") ||
        normalized.includes("database")
      ) {
        topics = [
          "SQL",
          "Queries",
          "Joins",
          "Database Design",
        ];

        description =
          "Learn database fundamentals and write efficient SQL queries.";

        duration = "1 week";
      }

      /* =====================================================
         GIT / GITHUB
      ===================================================== */

      else if (
        normalized.includes("git") ||
        normalized.includes("github")
      ) {
        topics = [
          "Git",
          "GitHub",
          "Branches",
          "Pull Requests",
        ];

        description =
          "Learn professional version control and collaborative GitHub workflows.";

        duration = "3–5 days";
      }

      /* =====================================================
         API / REST
      ===================================================== */

      else if (
        normalized.includes("api") ||
        normalized.includes("rest")
      ) {
        topics = [
          "HTTP",
          "REST",
          "JSON",
          "API Integration",
        ];

        description =
          "Learn how modern applications communicate using REST APIs.";

        duration = "1 week";
      }

      /* =====================================================
         PYTHON
      ===================================================== */

      else if (
        normalized.includes("python")
      ) {
        topics = [
          "Python",
          "OOP",
          "Libraries",
          "Projects",
        ];

        description =
          "Strengthen Python programming and apply it through practical projects.";

        duration = "1–2 weeks";
      }

      /* =====================================================
         DATA / PANDAS
      ===================================================== */

      else if (
        normalized.includes("data") ||
        normalized.includes("pandas")
      ) {
        topics = [
          "Data Analysis",
          "Pandas",
          "Visualization",
          "Projects",
        ];

        description =
          "Learn practical data analysis and visualization techniques.";

        duration = "2 weeks";
      }

      /* =====================================================
         JAVA
      ===================================================== */

      else if (
        normalized.includes("java")
      ) {
        topics = [
          "OOP",
          "Collections",
          "Exception Handling",
          "Projects",
        ];

        description =
          "Strengthen Java programming and object-oriented development skills.";

        duration = "1–2 weeks";
      }

      /* =====================================================
         CSS / TAILWIND
      ===================================================== */

      else if (
        normalized.includes("css") ||
        normalized.includes("tailwind")
      ) {
        topics = [
          "Responsive Design",
          "Flexbox",
          "Grid",
          "UI Design",
        ];

        description =
          "Improve responsive UI development and modern frontend styling.";

        duration = "1 week";
      }

      /* =====================================================
         HTML
      ===================================================== */

      else if (
        normalized.includes("html")
      ) {
        topics = [
          "Semantic HTML",
          "Forms",
          "Accessibility",
          "SEO",
        ];

        description =
          "Build accessible and well-structured web pages using modern HTML.";

        duration = "3–5 days";
      }

      return {
        title: `Master ${skill}`,
        description,
        duration,
        topics,
        completed: false,
      };
    });
}


export default LearningRoadmap;